/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HiIndexRouteImport } from './routes/hi/index'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'
import { Route as HiCategorySlugRouteImport } from './routes/hi/category/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HiIndexRoute = HiIndexRouteImport.update({
  id: '/hi/',
  path: '/hi/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HiCategorySlugRoute = HiCategorySlugRouteImport.update({
  id: '/hi/category/$slug',
  path: '/hi/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/category/$slug': typeof CategorySlugRoute
  '/hi/': typeof HiIndexRoute
  '/hi/category/$slug': typeof HiCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/category/$slug': typeof CategorySlugRoute
  '/hi': typeof HiIndexRoute
  '/hi/category/$slug': typeof HiCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/category/$slug': typeof CategorySlugRoute
  '/hi/': typeof HiIndexRoute
  '/hi/category/$slug': typeof HiCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/category/$slug' | '/hi/' | '/hi/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/category/$slug' | '/hi' | '/hi/category/$slug'
  id: '__root__' | '/' | '/category/$slug' | '/hi/' | '/hi/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategorySlugRoute: typeof CategorySlugRoute
  HiIndexRoute: typeof HiIndexRoute
  HiCategorySlugRoute: typeof HiCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hi/': {
      id: '/hi/'
      path: '/hi'
      fullPath: '/hi/'
      preLoaderRoute: typeof HiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hi/category/$slug': {
      id: '/hi/category/$slug'
      path: '/hi/category/$slug'
      fullPath: '/hi/category/$slug'
      preLoaderRoute: typeof HiCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategorySlugRoute: CategorySlugRoute,
  HiIndexRoute: HiIndexRoute,
  HiCategorySlugRoute: HiCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
